//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueba.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pruebaTecnicaEntities : DbContext
    {
        public pruebaTecnicaEntities()
            : base("name=pruebaTecnicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Finca> Finca { get; set; }
        public DbSet<Propietario> Propietario { get; set; }
        public DbSet<Residentes> Residentes { get; set; }
        public DbSet<Trabajador> Trabajador { get; set; }
        public DbSet<Trabajadorxfinca> Trabajadorxfinca { get; set; }
    }
}
