//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propietario
    {
        public int cedula { get; set; }
        public string nombre { get; set; }
        public string Apellido { get; set; }
        public string contacto { get; set; }
        public string departamento { get; set; }
        public Nullable<int> finca { get; set; }
    
        public virtual Finca Finca1 { get; set; }
    }
}
